name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Build, tag, and push the Docker image to ECR
      - name: Build, tag, and push Docker image
        run: |
          IMAGE_URI=${{ secrets.ECR_URI }}/nestjs-app:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      # Step 5: Update ECS service
      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster your-cluster-name \
            --service your-service-name \
            --force-new-deployment
